import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { ArrowRight, GraduationCap } from "lucide-react";
import { useAuth } from "../context/AuthContext.jsx";
import Logo from "../components/common/Logo.jsx";
import { schoolConfig } from "../config/school.config.js";

export default function PortalLogin() {
  const { login } = useAuth(); const navigate=useNavigate(); const location=useLocation(); const [identifier,setIdentifier]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function handleSubmit(e){e.preventDefault();setError("");setBusy(true);try{const user=await login(identifier,password);if(user.role!=="PARENT")throw new Error("This account is not a parent portal account.");navigate(location.state?.from?.pathname||"/portal",{replace:true})}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <main className="min-h-screen bg-cream px-4 py-8 sm:px-6 sm:py-12"><div className="mx-auto w-full max-w-5xl"><div className="mb-8 flex justify-center"><Logo/></div><div className="grid overflow-hidden rounded-3xl border border-line bg-surface shadow-[0_25px_70px_-45px_rgba(0,0,0,.55)] lg:grid-cols-2"><div className="bg-primary p-8 text-on-primary sm:p-10 lg:p-12"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/10 text-secondary-light"><GraduationCap size={24}/></span><p className="mt-10 text-xs font-semibold uppercase tracking-[.18em] text-secondary-light">Parent portal</p><h1 className="mt-3 font-display text-4xl leading-tight">Stay close to your child's school journey.</h1><p className="mt-5 text-sm leading-7 text-on-primary/75">View fee balances, pay securely online, access receipts and read published academic results.</p><div className="mt-10 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm text-on-primary/75">{schoolConfig.school.name}</div></div><div className="p-6 sm:p-10 lg:p-12"><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Welcome back</p><h2 className="mt-2 font-display text-3xl text-ink">Parent sign in</h2><p className="mt-2 text-sm leading-6 text-muted">Use the email or phone number provided by the school.</p><form onSubmit={handleSubmit} className="mt-7 space-y-4"><label className="block"><span className="mb-1.5 block text-xs font-semibold text-ink">Email or phone</span><input autoComplete="username" required className="field" value={identifier} onChange={e=>setIdentifier(e.target.value)}/></label><label className="block"><span className="mb-1.5 block text-xs font-semibold text-ink">Password</span><input autoComplete="current-password" required type="password" className="field" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700" role="alert">{error}</div>}<button disabled={busy} className="btn btn-primary w-full">{busy?"Signing in…":"Sign in to portal"}<ArrowRight size={17}/></button></form><Link to="/" className="mt-6 block text-center text-xs font-semibold text-link hover:underline">← Back to school website</Link></div></div></div></main>;
}
