import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import { portalApi } from "../api/portal.js";
import { formatNaira } from "../utils/format.js";
import PageHeader from "../components/dashboard/PageHeader.jsx";
import StatusBadge from "../components/dashboard/StatusBadge.jsx";
import EmptyState from "../components/dashboard/EmptyState.jsx";
import LoadingState from "../components/dashboard/LoadingState.jsx";

export default function PortalFees(){const [params]=useSearchParams();const studentId=params.get("student")||"";const [invoices,setInvoices]=useState(null),[error,setError]=useState("");useEffect(()=>{portalApi.invoices(studentId?{student:studentId}:{}).then(r=>setInvoices(r.invoices)).catch(e=>setError(e.message))},[studentId]);return <div className="space-y-6"><PageHeader eyebrow="Payments" title="Fees & invoices" description="Review every invoice for your children and open an invoice to make a secure payment."/>{error&&<div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}{!invoices&&!error?<LoadingState label="Loading invoices…"/>:invoices?.length===0?<EmptyState title="No invoices yet" description="The school will add an invoice when fees are raised for your child."/>:<div className="grid gap-4">{invoices.map(inv=><Link key={inv._id} to={`/portal/fees/${inv._id}`} className="group rounded-2xl border border-line bg-surface p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-semibold text-ink">{inv.invoiceNumber}</h2><StatusBadge value={inv.status}/></div><p className="mt-2 text-sm text-ink">{inv.student?.firstName} {inv.student?.lastName}</p><p className="mt-0.5 text-xs text-muted">{inv.session?.name} · {inv.term?.name}</p></div><div className="flex items-center justify-between gap-5 sm:justify-end"><div className="text-left sm:text-right"><p className="text-xs text-muted">Balance due</p><p className="mt-0.5 text-lg font-semibold text-ink">{formatNaira(inv.balance)}</p></div><ArrowRight size={18} className="text-muted transition group-hover:translate-x-1 group-hover:text-primary"/></div></div></Link>)}</div>}</div>}
