import { useEffect,useState } from "react";
import { Link } from "react-router-dom";
import { Receipt } from "lucide-react";
import { portalApi } from "../api/portal.js";
import { formatNaira,formatDate } from "../utils/format.js";
import PageHeader from "../components/dashboard/PageHeader.jsx";
import StatusBadge from "../components/dashboard/StatusBadge.jsx";
import EmptyState from "../components/dashboard/EmptyState.jsx";
import LoadingState from "../components/dashboard/LoadingState.jsx";
export default function PortalPayments(){const [payments,setPayments]=useState(null),[error,setError]=useState("");useEffect(()=>{portalApi.payments().then(r=>setPayments(r.payments)).catch(e=>setError(e.message))},[]);return <div className="space-y-6"><PageHeader eyebrow="Payments" title="Payment history" description="A record of online fee payments made from your parent account."/>{error&&<div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}{!payments&&!error?<LoadingState label="Loading payment history…"/>:payments?.length===0?<EmptyState title="No payments yet" description="Your successful online payments will appear here."/>:<section className="overflow-hidden rounded-2xl border border-line bg-surface shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="bg-cream/70 text-left text-[11px] uppercase tracking-[.12em] text-muted"><tr><th className="px-5 py-3">Student</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Date</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Receipt</th></tr></thead><tbody>{payments.map(p=><tr key={p._id} className="border-t border-line hover:bg-cream/40"><td className="px-5 py-4"><p className="font-medium text-ink">{p.student?.firstName} {p.student?.lastName}</p><p className="mt-0.5 text-xs text-muted">{p.invoice?.invoiceNumber||"Payment"}</p></td><td className="px-5 py-4 font-semibold text-ink">{formatNaira(p.amount)}</td><td className="px-5 py-4 text-muted">{formatDate(p.paidAt||p.createdAt)}</td><td className="px-5 py-4"><StatusBadge value={p.status}/></td><td className="px-5 py-4 text-right"><Link to={`/portal/receipts/${p._id}`} className="inline-flex items-center gap-1.5 text-xs font-semibold text-link hover:underline"><Receipt size={14}/> Receipt</Link></td></tr>)}</tbody></table></div></section>}</div>}
