import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { useAuth } from "../context/AuthContext.jsx";
import Logo from "../components/common/Logo.jsx";
import { schoolConfig } from "../config/school.config.js";

export default function AdminLogin() {
  const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [identifier,setIdentifier]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function handleSubmit(e){e.preventDefault();setError("");setBusy(true);try{const user=await login(identifier,password);if(user.role!=="ADMIN"&&user.role!=="STAFF")throw new Error("This account does not have staff dashboard access.");navigate(user.mustChangePassword?"/account/password":(location.state?.from?.pathname||(user.role==="STAFF"?"/staff":"/admin")),{replace:true})}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <main className="grid min-h-screen bg-canvas lg:grid-cols-[1.05fr_.95fr]">
    <section className="relative hidden overflow-hidden bg-primary p-10 text-on-primary lg:flex lg:flex-col lg:justify-between"><div className="absolute -right-28 -top-28 h-80 w-80 rounded-full border-[3rem] border-secondary/20"/><div className="relative"><Logo variant="light"/><div className="mt-24 max-w-xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-secondary-light">School management</p><h1 className="mt-4 font-display text-5xl leading-tight">Run the school with clarity.</h1><p className="mt-5 max-w-lg text-base leading-7 text-on-primary/75">Manage students, fees, academic records, results and parent communication from one focused workspace.</p></div></div><div className="relative text-sm text-on-primary/60">{schoolConfig.school.name}</div></section>
    <section className="flex items-center justify-center px-5 py-10 sm:px-8"><div className="w-full max-w-md"><div className="mb-10 lg:hidden"><Logo/></div><div className="rounded-3xl border border-line bg-surface p-6 shadow-[0_25px_70px_-45px_rgba(0,0,0,.55)] sm:p-8"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary"><ShieldCheck size={23}/></span><p className="mt-6 text-xs font-semibold uppercase tracking-[.16em] text-primary">Secure access</p><h2 className="mt-2 font-display text-3xl text-ink">Staff dashboard</h2><p className="mt-2 text-sm leading-6 text-muted">Sign in with your school administrator or staff account.</p><form onSubmit={handleSubmit} className="mt-7 space-y-4"><label className="block"><span className="mb-1.5 block text-xs font-semibold text-ink">Email or phone</span><input autoComplete="username" required className="field" value={identifier} onChange={e=>setIdentifier(e.target.value)} /></label><label className="block"><span className="mb-1.5 block text-xs font-semibold text-ink">Password</span><input autoComplete="current-password" required type="password" className="field" value={password} onChange={e=>setPassword(e.target.value)} /></label>{error&&<div className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700" role="alert">{error}</div>}<button disabled={busy} className="btn btn-primary w-full">{busy?"Signing in…":"Sign in"}<ArrowRight size={17}/></button></form></div><Link to="/" className="mt-5 block text-center text-xs font-semibold text-link hover:underline">← Back to school website</Link></div></section>
  </main>;
}
