import { useEffect, useState } from "react";
import { Save, Palette, CreditCard, SlidersHorizontal } from "lucide-react";
import { adminApi } from "../api/admin.js";
import PageHeader from "../components/dashboard/PageHeader.jsx";
import LoadingState from "../components/dashboard/LoadingState.jsx";

const FEATURE_LABELS = { onlinePayment: "Online payment", parentPortal: "Parent portal", results: "Results", admissions: "Admissions", gallery: "Gallery", news: "News" };

export default function AdminSettings() {
  const [settings,setSettings]=useState(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
  useEffect(()=>{adminApi.settings().then(r=>setSettings(r.settings)).catch(e=>setError(e.message))},[]);
  function set(field,value){setSettings(p=>({...p,[field]:value}))} function setFeature(key,value){setSettings(p=>({...p,features:{...p.features,[key]:value}}))}
  async function handleSubmit(e){e.preventDefault();setError("");setMessage("");setSaving(true);try{const res=await adminApi.updateSettings(settings);setSettings(res.settings);setMessage("School settings saved.")}catch(e){setError(e.message)}finally{setSaving(false)}}
  if(!settings) return <LoadingState label="Loading school settings…"/>;
  return <div className="space-y-6"><PageHeader eyebrow="Configuration" title="School settings" description="Operational identity used by the fees, receipts and parent portal. Public marketing content remains configurable in the reusable frontend config files."/>{error&&<div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>}<form onSubmit={handleSubmit} className="space-y-5">
    <Panel icon={Palette} title="School identity" description="Details parents see across operational screens and receipts."><div className="grid gap-4 sm:grid-cols-2"><Field label="School name"><input className="field" value={settings.schoolName||""} onChange={e=>set("schoolName",e.target.value)}/></Field><Field label="Logo URL"><input className="field" value={settings.logo||""} onChange={e=>set("logo",e.target.value)}/></Field><Field label="Phone"><input className="field" value={settings.phone||""} onChange={e=>set("phone",e.target.value)}/></Field><Field label="Email"><input type="email" className="field" value={settings.email||""} onChange={e=>set("email",e.target.value)}/></Field><Field label="WhatsApp"><input className="field" value={settings.whatsapp||""} onChange={e=>set("whatsapp",e.target.value)}/></Field><Field label="Address" wide><input className="field" value={settings.address||""} onChange={e=>set("address",e.target.value)}/></Field></div></Panel>
    <Panel icon={SlidersHorizontal} title="Feature controls" description="Enable operational modules for this school's installation."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(FEATURE_LABELS).map(([key,label])=><label key={key} className="flex cursor-pointer items-center gap-3 rounded-xl border border-line p-3 text-sm font-medium text-ink hover:bg-canvas/50"><input type="checkbox" className="h-4 w-4 accent-[var(--c-primary)]" checked={!!settings.features?.[key]} onChange={e=>setFeature(key,e.target.checked)}/>{label}</label>)}</div></Panel>
    <Panel icon={CreditCard} title="Payment policy" description="Control whether parents can make partial payments against outstanding invoices."><label className="flex cursor-pointer items-start gap-3 rounded-xl bg-canvas p-4"><input type="checkbox" className="mt-1 h-4 w-4 accent-[var(--c-primary)]" checked={!!settings.allowPartialPayment} onChange={e=>set("allowPartialPayment",e.target.checked)}/><span><span className="block text-sm font-semibold text-ink">Allow partial payments</span><span className="mt-1 block text-xs leading-5 text-muted">When enabled, parents can enter an amount up to the outstanding balance at checkout.</span></span></label><label className="mt-3 flex cursor-pointer items-start gap-3 rounded-xl bg-canvas p-4"><input type="checkbox" className="mt-1 h-4 w-4 accent-[var(--c-primary)]" checked={!!settings.requirePaidFeesToPublish} onChange={e=>set("requirePaidFeesToPublish",e.target.checked)}/><span><span className="block text-sm font-bold text-ink">Hold results until the term's fees are fully paid</span><span className="mt-0.5 block text-xs text-muted">When on, the administrator cannot approve and publish a result while that student's invoice for the term is unpaid. Turn off to publish results regardless of fees.</span></span></label></Panel>
    <div className="flex justify-end"><button disabled={saving} className="btn btn-primary"><Save size={17}/>{saving?"Saving…":"Save settings"}</button></div>
  </form></div>;
}
function Panel({icon:Icon,title,description,children}){return <section className="rounded-2xl border border-line bg-surface p-5 shadow-sm sm:p-6"><div className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon size={19}/></span><div><h2 className="font-semibold text-ink">{title}</h2><p className="mt-1 text-xs leading-5 text-muted">{description}</p></div></div><div className="mt-6">{children}</div></section>}
function Field({label,wide,children}){return <label className={`block ${wide?"sm:col-span-2":""}`}><span className="mb-1.5 block text-xs font-semibold text-ink">{label}</span>{children}</label>}
