import { useEffect, useState } from "react";
import { Plus, Trash2, Receipt, WalletCards } from "lucide-react";
import { Link } from "react-router-dom";
import { adminApi } from "../api/admin.js";
import { formatNaira, formatDate } from "../utils/format.js";
import PageHeader from "../components/dashboard/PageHeader.jsx";
import StatusBadge from "../components/dashboard/StatusBadge.jsx";
import EmptyState from "../components/dashboard/EmptyState.jsx";
import LoadingState from "../components/dashboard/LoadingState.jsx";

export default function AdminFees() {
  const [sessions,setSessions]=useState([]),[terms,setTerms]=useState([]),[classes,setClasses]=useState([]),[feeStructures,setFeeStructures]=useState(null),[invoices,setInvoices]=useState(null),[payments,setPayments]=useState(null);
  const [error,setError]=useState(""),[message,setMessage]=useState(""),[form,setForm]=useState({session:"",term:"",class:""}),[items,setItems]=useState([{name:"Tuition",amount:""}]),[saving,setSaving]=useState(false),[generatingId,setGeneratingId]=useState(null);
  function loadAll(){setError(""); Promise.all([adminApi.sessions(),adminApi.classes(),adminApi.feeStructures(),adminApi.invoices(),adminApi.payments()]).then(([s,c,f,i,p])=>{setSessions(s.sessions);setClasses(c.classes);setFeeStructures(f.feeStructures);setInvoices(i.invoices);setPayments(p.payments);}).catch(e=>setError(e.message));}
  useEffect(loadAll,[]); useEffect(()=>{if(form.session) adminApi.terms({session:form.session}).then(r=>setTerms(r.terms)).catch(e=>setError(e.message)); else setTerms([])},[form.session]);
  function updateItem(i,field,value){setItems(prev=>prev.map((it,idx)=>idx===i?{...it,[field]:value}:it))} function addItem(){setItems(p=>[...p,{name:"",amount:""}])} function removeItem(i){setItems(p=>p.filter((_,idx)=>idx!==i))} const total=items.reduce((sum,it)=>sum+(Number(it.amount)||0),0);
  async function handleSubmit(e){e.preventDefault();setError("");setMessage("");setSaving(true);try{const valid=items.filter(it=>it.name.trim()&&it.amount!=="").map(it=>({name:it.name.trim(),amount:Number(it.amount)}));if(!valid.length)throw new Error("Add at least one fee item.");await adminApi.createFeeStructure({...form,items:valid});setItems([{name:"Tuition",amount:""}]);setMessage("Fee structure created.");loadAll()}catch(e){setError(e.message)}finally{setSaving(false)}}
  async function handleGenerate(id){setGeneratingId(id);setError("");setMessage("");try{const res=await adminApi.generateInvoices({feeStructureId:id});setMessage(`Generated ${res.created} invoice(s).${res.skipped.length?` ${res.skipped.length} already existed.`:""}`);loadAll()}catch(e){setError(e.message)}finally{setGeneratingId(null)}}
  return <div className="space-y-6">
    <PageHeader eyebrow="Finance" title="Fees & invoices" description="Set term fees, generate student invoices and review payment activity." />
    {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>}
    <div className="grid gap-5 xl:grid-cols-[1.05fr_.95fr]">
      <section className="rounded-2xl border border-line bg-surface p-5 shadow-sm sm:p-6"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><WalletCards size={20}/></span><div><h2 className="font-semibold text-ink">New fee structure</h2><p className="mt-1 text-xs text-muted">Define fees once, then generate invoices for the matching class.</p></div></div><form onSubmit={handleSubmit} className="mt-6 space-y-4"><div className="grid gap-3 sm:grid-cols-3"><select required className="field" value={form.session} onChange={e=>setForm({...form,session:e.target.value,term:""})}><option value="">Session</option>{sessions.map(s=><option key={s._id} value={s._id}>{s.name}</option>)}</select><select required className="field" value={form.term} onChange={e=>setForm({...form,term:e.target.value})}><option value="">Term</option>{terms.map(t=><option key={t._id} value={t._id}>{t.name}</option>)}</select><select required className="field" value={form.class} onChange={e=>setForm({...form,class:e.target.value})}><option value="">Class</option>{classes.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select></div><div className="space-y-2">{items.map((it,i)=><div key={i} className="grid grid-cols-[minmax(0,1fr)_7rem_auto] gap-2"><input placeholder="Fee item" className="field" value={it.name} onChange={e=>updateItem(i,"name",e.target.value)}/><input type="number" min="0" placeholder="Amount" className="field" value={it.amount} onChange={e=>updateItem(i,"amount",e.target.value)}/><button type="button" onClick={()=>removeItem(i)} disabled={items.length===1} className="rounded-xl px-2 text-muted hover:bg-rose-50 hover:text-error disabled:opacity-30" aria-label="Remove item"><Trash2 size={17}/></button></div>)}</div><button type="button" onClick={addItem} className="btn btn-outline btn-sm"><Plus size={16}/> Add fee item</button><div className="flex items-center justify-between rounded-xl bg-cream p-4"><span className="text-sm font-medium text-muted">Structure total</span><span className="text-lg font-semibold text-ink">{formatNaira(total)}</span></div><button disabled={saving} className="btn btn-primary w-full">{saving?"Saving…":"Create fee structure"}</button></form></section>
      <section className="rounded-2xl border border-line bg-surface p-5 shadow-sm sm:p-6"><h2 className="font-semibold text-ink">Fee structures</h2><p className="mt-1 text-xs text-muted">Generate invoices after confirming each structure.</p>{feeStructures===null?<div className="mt-4"><LoadingState label="Loading fee structures…"/></div>:!feeStructures.length?<div className="mt-4"><EmptyState title="No fee structures" description="Create a fee structure for an active session and term."/></div>:<div className="mt-4 space-y-2">{feeStructures.map(fs=><div key={fs._id} className="rounded-xl border border-line p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-ink">{fs.class?.name} · {fs.term?.name}</p><p className="mt-1 text-xs text-muted">{fs.session?.name} · {formatNaira(fs.totalAmount)}</p></div><button onClick={()=>handleGenerate(fs._id)} disabled={generatingId===fs._id} className="btn btn-outline btn-sm">{generatingId===fs._id?"Generating…":"Generate invoices"}</button></div></div>)}</div>}</section>
    </div>
    <section className="overflow-hidden rounded-2xl border border-line bg-surface shadow-sm"><div className="border-b border-line p-5"><h2 className="text-sm font-semibold text-ink">Invoices</h2><p className="mt-0.5 text-xs text-muted">Every generated invoice and its current balance.</p></div>{invoices===null?<LoadingState label="Loading invoices…"/>:!invoices.length?<div className="p-5"><EmptyState title="No invoices" description="Generate invoices from a fee structure to see them here."/></div>:<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-cream/70 text-left text-[11px] uppercase tracking-[0.12em] text-muted"><tr><th className="px-5 py-3">Invoice</th><th className="px-5 py-3">Student</th><th className="px-5 py-3">Period</th><th className="px-5 py-3">Total</th><th className="px-5 py-3">Balance</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{invoices.map(inv=><tr key={inv._id} className="border-t border-line hover:bg-cream/40"><td className="px-5 py-4 font-medium text-ink">{inv.invoiceNumber}</td><td className="px-5 py-4 text-ink">{inv.student?.firstName} {inv.student?.lastName}<p className="text-xs text-muted">{inv.student?.admissionNumber}</p></td><td className="px-5 py-4 text-muted">{inv.session?.name} · {inv.term?.name}</td><td className="px-5 py-4 text-ink">{formatNaira(inv.totalAmount)}</td><td className="px-5 py-4 font-semibold text-ink">{formatNaira(inv.balance)}</td><td className="px-5 py-4"><StatusBadge value={inv.status}/></td></tr>)}</tbody></table></div>}</section>
    <section className="overflow-hidden rounded-2xl border border-line bg-surface shadow-sm"><div className="border-b border-line p-5"><h2 className="text-sm font-semibold text-ink">Recent payments</h2><p className="mt-0.5 text-xs text-muted">Successful and failed payment records.</p></div>{payments===null?<LoadingState label="Loading payments…"/>:!payments.length?<div className="p-5"><EmptyState title="No payment activity" description="Payments will appear here after parents use online checkout."/></div>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-cream/70 text-left text-[11px] uppercase tracking-[0.12em] text-muted"><tr><th className="px-5 py-3">Payment</th><th className="px-5 py-3">Student</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Date</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Receipt</th></tr></thead><tbody>{payments.map(p=><tr key={p._id} className="border-t border-line hover:bg-cream/40"><td className="px-5 py-4 font-mono text-xs text-muted">{p.reference}</td><td className="px-5 py-4 text-ink">{p.student?.firstName} {p.student?.lastName}</td><td className="px-5 py-4 font-semibold text-ink">{formatNaira(p.amount)}</td><td className="px-5 py-4 text-muted">{formatDate(p.paidAt||p.createdAt)}</td><td className="px-5 py-4"><StatusBadge value={p.status}/></td><td className="px-5 py-4 text-right"><Link to={`/admin/payments/${p._id}/receipt`} className="inline-flex items-center gap-1 text-xs font-semibold text-link hover:underline"><Receipt size={14}/> View</Link></td></tr>)}</tbody></table></div>}</section>
  </div>;
}
